{"name": "Авторизация с невалидными данными", "status": "passed", "description": "Авторизация с некорректными username и password", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1737978549957, "stop": 1737978551515}, {"name": "Ввести в форму некорректные данные: username: \"invalid_username\" и password: \"invalid_password\"", "status": "passed", "start": 1737978551515, "stop": 1737978554625}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1737978554625, "stop": 1737978554633}], "parameters": [{"name": "browser_name", "value": "'firefox'"}], "start": 1737978549957, "stop": 1737978554634, "uuid": "e66c60ab-8e95-4b9d-921b-a810b65698d7", "historyId": "04d0154d6cf7f6caeeb2523af1285c03", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "NB64-523"}, {"name": "thread", "value": "20700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}